importing model with surfactin

In [1]:
%run model_sucrose.ipynb

In [2]:
import numpy as np

In [3]:
from cameo.strain_design.deterministic.flux_variability_based import FSEOF
fseof = FSEOF(model)
result = fseof.run(target = model.reactions.DM_surfactin_c)
df = result.data_frame

In [ ]:
from matplotlib import pyplot as plt
result.data_frame.T.plot()
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.show()

In [4]:
# sorting 
df= df.sort_values([1], ascending = False)
 
# removing genes from dataframe 
removed_zero = (df[1] != 0)
df = df.loc[removed_zero]

df.head()

,1,2,3,4,5,6,7,8,9,10
ATPS4r,62.612368,57.187515,51.762662,46.337809,41.668253,37.249920,32.831587,28.413253,23.994920,20.282517
NADH4,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825
CYOO3,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825
CYOR3m,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825
GAPD,20.583523,19.533698,18.483873,17.434048,16.163779,14.812191,13.460603,12.109016,10.757428,9.854504

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
ATPS4r,62.612368,57.187515,51.762662,46.337809,41.668253,37.249920,32.831587,28.413253,23.994920,20.282517,1.676062
CYOR3m,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
CYOO3,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
NADH4,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
GAPD,20.583523,19.533698,18.483873,17.434048,16.163779,14.812191,13.460603,12.109016,10.757428,9.854504,1.521243
...,...,...,...,...,...,...,...,...,...,...,...
XYLI2,-5.631888,-5.339026,-5.046164,-4.753302,-4.447794,-4.136912,-3.826029,-3.515147,-3.204265,-3.042275,1.459813
SUCCt2r,-6.645558,-5.989211,-5.332865,-4.676519,-3.849059,-2.960066,-2.071073,-1.182080,-0.293086,0.000000,2.000000
PGM,-19.936114,-18.844353,-17.752591,-16.660830,-15.348626,-13.955102,-12.561578,-11.168054,-9.774530,-8.829671,1.557102
PGK,-20.583523,-19.533698,-18.483873,-17.434048,-16.163779,-14.812191,-13.460603,-12.109016,-10.757428,-9.854504,1.521243
H2Ot,-28.548917,-27.205035,-25.861154,-24.517272,-23.364948,-22.275488,-21.186028,-20.096569,-19.007109,-18.089174,1.366380

In [ ]:
def bar_color(df,color1,color2):
    return np.where(df.values >=0,color1,color2).T

fig = df.plot(legend=None, kind='bar', color=bar_color(df,'g','r'),figsize=(20, 4), grid =False);
fig.set_ylabel('Change in flux')
fig.set_xlabel('Gene names')
fig.set_title('Flux scanning based on Enforced Objective Flux', size=30)

ValueError: Invalid color ['g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r']

In [23]:
df['relative_change_in_flux'] = (df[10]-df[1])/df[1]

In [14]:
#target_reactions_df = df[df['relative_change_in_flux'] > 1.8]

In [19]:
df = df.drop('DM_surfactin_c')

In [24]:
df= df.sort_values(['relative_change_in_flux'], ascending = False)

In [45]:
df[0:10]

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
GLYO1,0.029897,0.062262,0.094627,0.126992,0.159357,0.191722,0.224087,0.256452,0.288817,0.520449,16.408068
GART,0.030105,0.062450,0.094794,0.127139,0.159483,0.191827,0.224172,0.256516,0.288860,0.332798,10.054576
RPE,0.194107,0.174909,0.155712,0.136514,0.457035,0.897201,1.337368,1.777534,2.217701,2.108236,9.861205
MOHMT,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
DPCOAK,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
PPNCL,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
PANTS,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
ASP1DC,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
DPR,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969
PPCDC,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,8.999969

In [27]:
df = target_reactions_df.drop(labels='relative_change_in_flux', axis=1)

In [ ]:
fig = df.T.plot(cmap="viridis",figsize=(8, 8), grid =True, linewidth=3);
fig.legend(loc='center left', bbox_to_anchor=(1, 0.5))
fig.set_ylabel('Flux')
fig.set_title('Reactions with a relative change in Flux > 80%', size=20)

Text(0.5, 1.0, 'Reactions with a relative change in Flux > 80%')

In [10]:
#lowest flux reactions
df.tail()

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
KARA1,-0.604206,-0.756380,-0.908555,-1.060729,-1.212903,-1.365078,-1.517252,-1.669426,-1.821601,-1.973775,-1.973775
XYLI2,-5.631888,-5.339026,-5.046164,-4.753302,-4.447794,-4.136912,-3.826029,-3.515147,-3.204265,-3.042275,-3.042275
PGM,-19.936114,-18.844353,-17.752591,-16.660830,-15.348626,-13.955102,-12.561578,-11.168054,-9.774530,-8.829671,-8.829671
PGK,-20.583523,-19.533698,-18.483873,-17.434048,-16.163779,-14.812191,-13.460603,-12.109016,-10.757428,-9.854504,-9.854504
H2Ot,-28.548917,-27.205035,-25.861154,-24.517272,-23.364948,-22.275488,-21.186028,-20.096569,-19.007109,-18.089174,-18.089174

In [22]:
#higest flux reactions
df.head()

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
GLYO1,0.029897,0.062262,0.094627,0.126992,0.159357,0.191722,0.224087,0.256452,0.288817,0.520449,17.408068
GART,0.030105,0.062450,0.094794,0.127139,0.159483,0.191827,0.224172,0.256516,0.288860,0.332798,11.054576
RPE,0.194107,0.174909,0.155712,0.136514,0.457035,0.897201,1.337368,1.777534,2.217701,2.108236,10.861205
PNTK,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,9.999969
MOHMT,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,9.999969

In [26]:
model.reactions.RPE

In [27]:
model.optimize()

In [28]:
model.reactions.GLYO1.flux

1.8919343064769113e-15

In [30]:
with model:
    model.reactions.GLYO1.lower_bound = 0.520449
    solution = model.optimize()

In [33]:
solution

In [35]:
with model:
    model.objective = "DM_surfactin_c"
    print(model.slim_optimize())
    print(model.reactions.GLYO1.flux)
    model.reactions.GLYO1.lower_bound = 0.520449
    print(model.slim_optimize()) 
    print(model.reactions.GLYO1.flux)

0.35714285714285093
1.947610962891021
0.35714285714285093
1.9476109628910208

In [44]:
#increase flux of possible upregulation target to at least the flux found in FSEOF
with model:
    print(model.slim_optimize())
    print(model.reactions.GLYO1.flux)
    print(model.reactions.DM_surfactin_c.flux)
    model.reactions.GLYO1.lower_bound = 0.52
    print(model.slim_optimize()) 
    print(model.reactions.GLYO1.flux)
    print(model.reactions.DM_surfactin_c.flux)

0.6241848146321084
0.6050129780506668
2.9378221196004113e-15
0.6241848146321084
0.6050129780506668
2.9378221196004113e-15

In [40]:
with model:
    print(model.slim_optimize())
    print(model.reactions.GART.flux)
    print(model.reactions.DM_surfactin_c.flux)
    model.reactions.GART.lower_bound = 0.33
    print(model.slim_optimize()) 
    print(model.reactions.GART.flux)
    print(model.reactions.DM_surfactin_c.flux)

0.6241848146321082
0.0
3.823365439135255e-15
0.6241848146321086
0.33
3.893290820063424e-15

In [41]:
with model:
    print(model.slim_optimize())
    print(model.reactions.RPE.flux)
    print(model.reactions.DM_surfactin_c.flux)
    model.reactions.RPE.lower_bound = 2.11
    print(model.slim_optimize()) 
    print(model.reactions.RPE.flux)
    print(model.reactions.DM_surfactin_c.flux)

0.6241848146321082
9.260667041405112
3.823365439135255e-15
0.6241848146321081
9.260667041405114
2.91664608369849e-15

In [42]:
with model:
    print(model.slim_optimize())
    print(model.reactions.PNTK.flux)
    print(model.reactions.DM_surfactin_c.flux)
    model.reactions.PNTK.lower_bound = 0.32
    print(model.slim_optimize()) 
    print(model.reactions.PNTK.flux)
    print(model.reactions.DM_surfactin_c.flux)

0.6241848146321082
1.6210534751678688e-15
3.823365439135255e-15
0.06491522072173918
0.32
0.32000000000000023