importing model with surfactin

In [1]:
%run model_sucrose.ipynb

In [2]:
import numpy as np

In [78]:
from cameo.strain_design.deterministic.flux_variability_based import FSEOF
fseof = FSEOF(model)
result = fseof.run(target = model.reactions.DM_surfactin_c)
df = result.data_frame

In [ ]:
from matplotlib import pyplot as plt
result.data_frame.T.plot()
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.show()

In [84]:
# sorting 
df= df.sort_values([1], ascending = False)
 
# removing genes from dataframe 
removed_zero = (df[1] != 0)
df = df.loc[removed_zero]

df.head()

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
ATPS4r,62.612368,57.187515,51.762662,46.337809,41.668253,37.249920,32.831587,28.413253,23.994920,20.282517,1.676062
CYOO3,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
CYOR3m,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
NADH4,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
GAPD,20.583523,19.533698,18.483873,17.434048,16.163779,14.812191,13.460603,12.109016,10.757428,9.854504,1.521243

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
ATPS4r,62.612368,57.187515,51.762662,46.337809,41.668253,37.249920,32.831587,28.413253,23.994920,20.282517,1.676062
CYOR3m,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
CYOO3,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
NADH4,37.472065,34.290564,31.109064,27.927563,25.153216,22.513634,19.874052,17.234470,14.594888,12.443825,1.667917
GAPD,20.583523,19.533698,18.483873,17.434048,16.163779,14.812191,13.460603,12.109016,10.757428,9.854504,1.521243
...,...,...,...,...,...,...,...,...,...,...,...
XYLI2,-5.631888,-5.339026,-5.046164,-4.753302,-4.447794,-4.136912,-3.826029,-3.515147,-3.204265,-3.042275,1.459813
SUCCt2r,-6.645558,-5.989211,-5.332865,-4.676519,-3.849059,-2.960066,-2.071073,-1.182080,-0.293086,0.000000,2.000000
PGM,-19.936114,-18.844353,-17.752591,-16.660830,-15.348626,-13.955102,-12.561578,-11.168054,-9.774530,-8.829671,1.557102
PGK,-20.583523,-19.533698,-18.483873,-17.434048,-16.163779,-14.812191,-13.460603,-12.109016,-10.757428,-9.854504,1.521243
H2Ot,-28.548917,-27.205035,-25.861154,-24.517272,-23.364948,-22.275488,-21.186028,-20.096569,-19.007109,-18.089174,1.366380

In [ ]:
def bar_color(df,color1,color2):
    return np.where(df.values >=0,color1,color2).T

fig = df.plot(legend=None, kind='bar', color=bar_color(df,'g','r'),figsize=(20, 4), grid =False);
fig.set_ylabel('Change in flux')
fig.set_xlabel('Gene names')
fig.set_title('Flux scanning based on Enforced Objective Flux', size=30)

ValueError: Invalid color ['g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g'
 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r' 'r'
 'r' 'r' 'r' 'r' 'r' 'r' 'r']

In [85]:
df['relative_change_in_flux'] = abs((df[10]-df[1])/df[1]) +1

In [14]:
#target_reactions_df = df[df['relative_change_in_flux'] > 1.8]

In [86]:
df= df.sort_values(['relative_change_in_flux'], ascending = False)

In [87]:
df

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
GLYO1,0.029897,0.062262,0.094627,0.126992,0.159357,0.191722,0.224087,0.256452,0.288817,0.520449,17.408068
GART,0.030105,0.062450,0.094794,0.127139,0.159483,0.191827,0.224172,0.256516,0.288860,0.332798,11.054576
RPE,0.194107,0.174909,0.155712,0.136514,0.457035,0.897201,1.337368,1.777534,2.217701,2.108236,10.861205
DM_surfactin_c,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,10.000000
PPNCL,0.032143,0.064286,0.096429,0.128571,0.160714,0.192857,0.225000,0.257143,0.289286,0.321429,9.999969
...,...,...,...,...,...,...,...,...,...,...,...
ACCOAC,2.777609,2.362066,1.946523,1.530981,1.539459,1.696638,1.853818,2.010998,2.168177,2.003928,1.278542
ASPTA,-1.321187,-1.331807,-1.342428,-1.353048,-1.363669,-1.374289,-1.384910,-1.395530,-1.406151,-1.627632,1.231947
PPA,1.923690,1.854603,1.785516,1.716429,1.708233,1.720912,1.733591,1.746270,1.758948,2.193348,1.140177
NDPK3,0.328040,0.330919,0.333797,0.336675,0.339554,0.342432,0.345310,0.348188,0.351067,0.353945,1.078969
NH4t,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1.000000

In [27]:
df = target_reactions_df.drop(labels='relative_change_in_flux', axis=1)

In [ ]:
fig = df.T.plot(cmap="viridis",figsize=(8, 8), grid =True, linewidth=3);
fig.legend(loc='center left', bbox_to_anchor=(1, 0.5))
fig.set_ylabel('Flux')
fig.set_title('Reactions with a relative change in Flux > 80%', size=20)

Text(0.5, 1.0, 'Reactions with a relative change in Flux > 80%')

In [12]:
#lowest flux reactions
target_reactions_df.tail()

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
HACD2,-0.266172,-0.184406,-0.102640,-0.020875,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,0.0,inf
ACACT7r,-0.269839,-0.187710,-0.105582,-0.023454,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,inf
HACD7,-0.301982,-0.251996,-0.202011,-0.152025,-0.160714,-0.192857,-0.225000,-0.257143,-0.289286,0.0,inf
ECOAH7,-0.301982,-0.251996,-0.202011,-0.152025,-0.160714,-0.192857,-0.225000,-0.257143,-0.289286,0.0,inf
SUCCt2r,-6.645558,-5.989211,-5.332865,-4.676519,-3.849059,-2.960066,-2.071073,-1.182080,-0.293086,0.0,inf

In [13]:
#higest flux reactions
target_reactions_df.head()

,1,2,3,4,5,6,7,8,9,10,relative_change_in_flux
PGL,0.680228,0.648274,0.616321,0.584367,1.061991,1.719083,2.376175,3.033267,3.690359,3.733866,1.817822
GND,0.680228,0.648274,0.616321,0.584367,1.061991,1.719083,2.376175,3.033267,3.690359,3.733866,1.817822
G6PDH2r,0.680228,0.648274,0.616321,0.584367,1.061991,1.719083,2.376175,3.033267,3.690359,3.733866,1.817822
ACOAD7,0.301982,0.251996,0.202011,0.152025,0.160714,0.192857,0.225000,0.257143,0.289286,-0.000000,inf
TKT1,0.194107,0.174909,0.155712,0.136514,0.287176,0.497661,0.708145,0.918630,1.129114,1.064783,1.817703